### ISSUE TITLE
getting SSL error when starting launcher

### ISSUE THREAD

**Issue by JanAbraham** [Drakkar-Software/OctoBot-Launcher#37]
Hi,

I am getting following error when starting OctoBot-Launcher. Can you help?

Merci,
Jan

**Comment by GuillaumeDSM** [comment]
Hi JanAbraham,

What version are you using ? Binary / Python ?

**Comment by JanAbraham** [comment]
many thanks for your fast reply.

I am using the Python version.

**Comment by JanAbraham** [comment]
I am on Mac-OS Mojave

**Comment by GuillaumeDSM** [comment]
Did you install the requirements (python -m pip install -r requirements.txt)

**Comment by JanAbraham** [comment]
yes, I did and there were no errors :-)

**Comment by GuillaumeDSM** [comment]
ok, maybe there is a missing dependancy on the Mac-OS version, what is the error line exactly ?

**Comment by JanAbraham** [comment]
Here is the whole output when starting OctoBot-Launcher:

(env) Jans-Mac-mini:octobot Jan$ OctoBot-Launcher
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jan/Dropbox/Programming/octobot/env/bin/OctoBot-Launcher", line 10, in <module>
    sys.exit(main())
  File "/Users/Jan/Dropbox/Programming/octobot/env/lib/python3.7/site-packages/entrypoint.py", line 87, in main
    update_launcher()
  File "/Users/Jan/Dropbox/Programming/octobot/env/lib/python3.7/site-packages/entrypoint.py", line 77, in update_launcher
    download_latest_release_sources()
  File "/Users/Jan/Dropbox/Programming/octobot/env/lib/python3.7/site-packages/entrypoint.py", line 42, in download_latest_release_sources
    urlretrieve(get_latest_source_url(), get_latest_release_source_file())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

**Comment by GuillaumeDSM** [comment]
Can you try this:
Once upon a time I stumbled with this issue. If you're using macOS go to Macintosh HD > Applications > Python3.6 folder (or whatever version of python you're using) > double click on "Install Certificates.command" file. :D

1st answer from https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

**Comment by JanAbraham** [comment]
you are a Genius!

SSL issue solved!

unfortunately I was running into another issue :-(

(env) Jans-Mac-mini:octobot Jan$ octobot-launcher
Traceback (most recent call last):
  File "/Users/Jan/Dropbox/Programming/octobot/env/lib/python3.7/site-packages/entrypoint.py", line 91, in main
    from launcher.launcher_entry import launcher
ModuleNotFoundError: No module named 'launcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jan/Dropbox/Programming/octobot/env/bin/octobot-launcher", line 10, in <module>
    sys.exit(main())
  File "/Users/Jan/Dropbox/Programming/octobot/env/lib/python3.7/site-packages/entrypoint.py", line 93, in main
    importlib.import_module("launcher.app.launcher_app")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'launcher'

Could you help with that too?

**Comment by GuillaumeDSM** [comment]
Oh, you used pip to install the launcher, I'm not sure it works on Mac OS, I suggest you use the code directly: clone or download the code, go to the OctoBot-Launcher folder and call entrypoint.py from python directly

**Comment by JanAbraham** [comment]
VOILA!!

It works!!

Thank you sooo much! Highly appreciate it! Can I send you a little incentive somewhere!

**Comment by JanAbraham** [comment]
Can I send you a little incentive somewhere?

**Comment by GuillaumeDSM** [comment]
You mean donation ? There are addresses in the footer of OctoBot, when you will run it :)

Now that I think about it, if you are on MacOS, the binary version, which is downloaded by the launcher has not yet been tested on MacOS.
If you have any trouble, I suggest you use the code version (https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only)

**Comment by JanAbraham** [comment]
you are right. this finally worked! OctoBot is running :-)

And I found the donation info :-))

Thanks a lot again!

**Comment by GuillaumeDSM** [comment]
Amazing, thanks for using OctoBot !
