### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by Endogen** [Drakkar-Software/OctoBot-Launcher#39]
Hey there,

i might understand it wrong but my impression was that i just need to install and start OctoBot-Launcher and i will be able to install OctoBot that way.

After i installed the launcher via
```
python3 -m pip install OctoBot-Launcher
```
and trying to start it with
```
octobot-launcher
```
I get this error:
```
INFO:root:Launcher updated
INFO:root:Launcher fresh install...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/entrypoint.py", line 91, in main
    from launcher.launcher_entry import launcher
ModuleNotFoundError: No module named 'launcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/octobot-launcher", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/entrypoint.py", line 93, in main
    importlib.import_module("launcher.app.launcher_app")
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'launcher'
```

**Comment by Herklos** [comment]
Hi @Endogen !
Thank for reporting, I'm fixing the issue.
