### ISSUE TITLE
Not possible to update OctoBot via Launcher on macOS

### ISSUE THREAD

**Issue by Endogen** [Drakkar-Software/OctoBot-Launcher#43]
I can start the launcher but if i choose to install the newest OctoBot version, then things start to fall apart.

Following error:
```
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /progress HTTP/1.1" 200 -
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /progress HTTP/1.1" 200 -
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /progress HTTP/1.1" 200 -
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /progress HTTP/1.1" 200 -
ERROR:flask.app:Exception on /install [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/launcher/app/app_controller.py", line 68, in install
    launcher_instance.update_bot(launcher_module.bot_instance)
  File "/usr/local/lib/python3.7/site-packages/launcher/app/launcher_app.py", line 94, in update_bot
    environment.install_bot(force_package=force_package)
  File "/usr/local/lib/python3.7/site-packages/launcher/tools/environment.py", line 96, in install_bot
    update_tentacles(executable_path, force_install=True)
  File "/usr/local/lib/python3.7/site-packages/launcher/tools/environment.py", line 140, in update_tentacles
    executor.execute_command_on_current_binary(binary_path, ["-p", "install", "all", "force"])
  File "/usr/local/lib/python3.7/site-packages/launcher/tools/executor.py", line 26, in execute_command_on_current_binary
    return subprocess.Popen(cmd, stdout=PIPE).stdout.read().rstrip().decode()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './OctoBot'
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /progress HTTP/1.1" 200 -
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /install HTTP/1.1" 500 -
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET / HTTP/1.1" 200 -
ERROR:flask.app:Exception on /bot [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/launcher/app/app_controller.py", line 39, in bot
    local_version = OctoBotVersion().get_current_version()
  File "/usr/local/lib/python3.7/site-packages/launcher/tools/version.py", line 83, in get_current_version
    return executor.execute_command_on_current_binary(binary_path, ["--version"]).split("\r\n")[0]
  File "/usr/local/lib/python3.7/site-packages/launcher/tools/executor.py", line 26, in execute_command_on_current_binary
    return subprocess.Popen(cmd, stdout=PIPE).stdout.read().rstrip().decode()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './OctoBot'
INFO:werkzeug:192.168.178.31 - - [19/Jun/2019 22:03:11] "GET /bot HTTP/1.1" 500 -
```

It seems that there is no `OctoBot` folder since all the subfolders are in my user-folder. Maybe it has something todo with that.

**Comment by Herklos** [comment]
Hi @Endogen ! Do you have a file named `OctoBot` in your installation directory ?

**Comment by Endogen** [comment]
There is such a binary file in my user-folder, yes.

**Comment by Herklos** [comment]
> There is such a binary file in my user-folder, yes.

Currently the macOS version of OctoBot and OctoBot launcher is not totally stable so you may need to run some additional commands to install OctoBot properly.

I suggest you open a terminal and run `chmod +x OctoBot`.

**Comment by r-hou** [comment]
> > There is such a binary file in my user-folder, yes.
> 
> Currently the macOS version of OctoBot and OctoBot launcher is not totally stable so you may need to run some additional commands to install OctoBot properly.
> 
> I suggest you open a terminal and run `chmod +x OctoBot`.

I have the same problem on Mac. `chmod +x OctoBot` doesn't work. I have tried excute `./OctoBot` in the terminal and returns "cannot execute binary file".
