### ISSUE TITLE
without binary OS - issue

### ISSUE THREAD

**Issue by riffaultsimon** [Drakkar-Software/OctoBot-Launcher#49]
Without binary
Install Python 3.7 and then type in a command line :

$ python -m pip install OctoBot-Launcher
$ octobot-launcher
__________

MBP-de-bibi:~ bibi$ python3 --version
Python 3.7.3
MBP-de-bibi:~ bibi$ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> python -m pip install OctoBot-Launcher
  File "<stdin>", line 1
    python -m pip install OctoBot-Launcher
                ^
SyntaxError: invalid syntax

i have installed python 3.7 but the command do not seem to work (see above syntax error). Do you have some hints? Also are there requirements as to where i should place the repository? 

Many thanks for your time !

**Comment by GuillaumeDSM** [comment]
Can you try wuth python3 -m pip install OctoBot-Launcher please ?

**Comment by riffaultsimon** [comment]
i get the same error

**Comment by riffaultsimon** [comment]
no wait it worked after restarting the command line, i get to other errors after the second command; let me check and will revert if it is blocking. Thanks for your help!

**Comment by riffaultsimon** [comment]
it seems i have SSL certificate issue, it that a known issue?

MBP-de-Simon:~ simonriffault$ octobot-launcher
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/octobot-launcher", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/entrypoint.py", line 87, in main
    update_launcher()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/entrypoint.py", line 77, in update_launcher
    download_latest_release_sources()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/entrypoint.py", line 42, in download_latest_release_sources
    urlretrieve(get_latest_source_url(), get_latest_release_source_file())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

**Comment by GuillaumeDSM** [comment]
I never got this issue with the launcher, what happens if you clone/download the code from this repo and call entrypoint.py with python ?

**Comment by riffaultsimon** [comment]
i use a work wifi maybe there are limitations due to that (i'll retry the normal way tonight at home). I have actually already dl the repo but i am not sure if i should place it somewhere precise to then invoke properly does it matter?

**Comment by riffaultsimon** [comment]
in pycharm i launched the entrypoint.py and got this:

Error when creating minimum launcher environment: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)> this should not prevent launcher from working.
ERROR:root:Can't start gui, please try command line interface (use --help).
[Errno 8] nodename nor servname provided, or not known

Process finished with exit code 0

in the commandline i get an error with the file location i am not sure how to correctly point at it

MBP-de-Simon:~ simonriffault$ python3 entrypoint.py
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'entrypoint.py': [Errno 2] No such file or directory

**Comment by riffaultsimon** [comment]
i've tried home on my personal wifi but get same (SSL) error with the command octobot-launcher :-(

**Comment by GuillaumeDSM** [comment]
That's really wierd, are you calling entrypoint.py from the entrypoint.py folder ?

**Comment by riffaultsimon** [comment]
i guess that's my issue i need to dig how to properly refer to it in the command line i will look it up and see if i find i ll keep you posted

**Comment by riffaultsimon** [comment]
when i do the following command it does not find it. Is there a specific place where i should put the folder? 

MBP-de-Simon:~ simonriffault$ /Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 16: import: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 17: import: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 18: import: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 19: import: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 20: import: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 21: import: command not found
from: can't read /var/mail/urllib.request
from: can't read /var/mail/past.translation
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 26: LAUNCHER_PATH: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 27: LAUNCHER_ENTRY_POINT: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 28: RELEASE_PATH: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 29: LAUNCHER_SOURCE_EXT: command not found
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 30: syntax error near unexpected token `os.path.dirname'
/Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py: line 30: `sys.path.append(os.path.dirname(sys.executable))'

**Comment by riffaultsimon** [comment]
and when i execute the file from pycharm (not sure i should do this), i get to the octobot landing page, but cannot really do anything from there:
- i can press either 'install octobot' but nothing happens (on left hand side the yellow bit remains at "not installed"
- on right hand side the two buttons restart launcher and stop launcher can be pressed but nothing there

**Comment by Herklos** [comment]
Hi @riffaultsimon, did your OctoBot installation succeed ? You can press 'start OctoBot' ?

**Comment by riffaultsimon** [comment]
Nope it did not. Quick question, is there an obvious error in addressing the path in the command below? (i saved the repo on my desktop) Second one, do i need to save it in a particuliar location?

MBP-de-Simon:~ simonriffault$ /Users/simonriffault/Desktop/OctoBot-Launcher-master/entrypoint.py

**Comment by GuillaumeDSM** [comment]
Can you try to call entrypoint.py from the OctoBot-Launcher-master directory directly ?

**Comment by riffaultsimon** [comment]
same thing it does not find it

**Comment by GuillaumeDSM** [comment]
The issue might come from the fact that you are on macOS, the binary version is not tested yet on this platform, what happens if you download OctoBot from https://github.com/Drakkar-Software/OctoBot-Binary/releases and put it in the launcher directory under the name OctoBot ?

**Comment by Herklos** [comment]
Hi @cubissimo, what is your issue ?
