### ISSUE TITLE
Failed to update balance : binanceus {"code":-1131,"msg":"'recvWindow' must be less than 60000."}

### ISSUE THREAD

**Issue by nathanp83** [Drakkar-Software/OctoBot-Launcher#55]
OctoBot Launcher     cli.py:103      Version : 0.4.0a24
Running on Windows:10:AMD64 with binary

This error is constantly happening.  I recreated my API key for binance.us as well thinking that would resolve it.

When forcing refresh on portfolio I observer this error:
2020-11-09 07:51:34 ERROR  tentacles.Services.Interfaces.web_interface app.py:1891     Exception on /api/refresh_portfolio [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "C:\OctoBot\tentacles\Services\Interfaces\web_interface\login\web_login_manager.py", line 63, in decorated_view
    return func(*args, **kwargs)
  File "C:\OctoBot\tentacles\Services\Interfaces\web_interface\api\trading.py", line 51, in refresh_portfolio
    interfaces_util.trigger_portfolios_refresh()
  File "octobot_services\interfaces\util\portfolio.py", line 117, in trigger_portfolios_refresh
  File "octobot_services\interfaces\util\util.py", line 51, in run_in_bot_main_loop
  File "octobot\octobot_api.py", line 61, in octobot.octobot_api.OctoBotAPI.run_in_main_asyncio_loop
  File "octobot\octobot_api.py", line 62, in octobot.octobot_api.OctoBotAPI.run_in_main_asyncio_loop
  File "octobot\octobot.py", line 151, in octobot.octobot.OctoBot.run_in_main_asyncio_loop
  File "octobot\octobot.py", line 152, in octobot.octobot.OctoBot.run_in_main_asyncio_loop
  File "octobot\task_manager.py", line 103, in octobot.task_manager.TaskManager.run_in_main_asyncio_loop
  File "octobot_commons\asyncio_tools.py", line 49, in run_coroutine_in_asyncio_loop
  File "octobot_commons\asyncio_tools.py", line 34, in run_coroutine_in_asyncio_loop
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "octobot_trading\api\portfolio.py", line 39, in refresh_real_trader_portfolio
  File "octobot_trading\personal_data\portfolios\channel\balance.py", line 56, in refresh_real_trader_portfolio
  File "octobot_trading\personal_data\portfolios\channel\balance.py", line 68, in _update_portfolio_from_exchange
  File "octobot_trading\exchanges\implementations\ccxt_exchange.py", line 130, in get_balance
  File "ccxt\async_support\binance.py", line 846, in fetch_balance
  File "ccxt\async_support\binance.py", line 2403, in request
  File "ccxt\async_support\base\exchange.py", line 95, in fetch2
  File "ccxt\async_support\base\exchange.py", line 148, in fetch
  File "ccxt\async_support\binance.py", line 2397, in handle_errors
  File "ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
ccxt.base.errors.BadRequest: binanceus {"code":-1131,"msg":"'recvWindow' must be less than 60000."}
2020-11-09 07:51:34 ERROR  WebInterfaceErrorHandler errors.py:34       binanceus {"code":-1131,"msg":"'recvWindow' must be less than 60000."}
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "C:\OctoBot\tentacles\Services\Interfaces\web_interface\login\web_login_manager.py", line 63, in decorated_view
    return func(*args, **kwargs)
  File "C:\OctoBot\tentacles\Services\Interfaces\web_interface\api\trading.py", line 51, in refresh_portfolio
    interfaces_util.trigger_portfolios_refresh()
  File "octobot_services\interfaces\util\portfolio.py", line 117, in trigger_portfolios_refresh
  File "octobot_services\interfaces\util\util.py", line 51, in run_in_bot_main_loop
  File "octobot\octobot_api.py", line 61, in octobot.octobot_api.OctoBotAPI.run_in_main_asyncio_loop
  File "octobot\octobot_api.py", line 62, in octobot.octobot_api.OctoBotAPI.run_in_main_asyncio_loop
  File "octobot\octobot.py", line 151, in octobot.octobot.OctoBot.run_in_main_asyncio_loop
  File "octobot\octobot.py", line 152, in octobot.octobot.OctoBot.run_in_main_asyncio_loop
  File "octobot\task_manager.py", line 103, in octobot.task_manager.TaskManager.run_in_main_asyncio_loop
  File "octobot_commons\asyncio_tools.py", line 49, in run_coroutine_in_asyncio_loop
  File "octobot_commons\asyncio_tools.py", line 34, in run_coroutine_in_asyncio_loop
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "octobot_trading\api\portfolio.py", line 39, in refresh_real_trader_portfolio
  File "octobot_trading\personal_data\portfolios\channel\balance.py", line 56, in refresh_real_trader_portfolio
  File "octobot_trading\personal_data\portfolios\channel\balance.py", line 68, in _update_portfolio_from_exchange
  File "octobot_trading\exchanges\implementations\ccxt_exchange.py", line 130, in get_balance
  File "ccxt\async_support\binance.py", line 846, in fetch_balance
  File "ccxt\async_support\binance.py", line 2403, in request
  File "ccxt\async_support\base\exchange.py", line 95, in fetch2
  File "ccxt\async_support\base\exchange.py", line 148, in fetch
  File "ccxt\async_support\binance.py", line 2397, in handle_errors
  File "ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
ccxt.base.errors.BadRequest: binanceus {"code":-1131,"msg":"'recvWindow' must be less than 60000."}
2020-11-09 07:51:34 ERROR  WebInterfaceErrorHandler errors.py:34       Error when displaying page: binanceus {"code":-1131,"msg":"'recvWindow' must be less than 60000."}

**Comment by Herklos** [comment]
Hi @nathanp83, thanks for using OctoBot. Please have a look at https://github.com/Drakkar-Software/OctoBot/wiki/Installation-Troubleshoot#time-synchronization, it should fix your issue.

<blockquote><img src="https://avatars3.githubusercontent.com/u/38042178?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Drakkar-Software/OctoBot">Drakkar-Software/OctoBot</a></strong></div><div>Cryptocurrency trading bot: high frequency, daily trading, social trading, ... - Drakkar-Software/OctoBot</div></blockquote>

**Comment by nathanp83** [comment]
Thank you for the quick response.  Unfortunately, that did not resolve the issue.

I tried both, Terminal (Admin) and installing the NTS application.  Error is still happening.

**Comment by GuillaumeDSM** [comment]
Hi,
Then doing something like [this](https://github.com/Drakkar-Software/OctoBot-Tentacles/blob/0.4.0/Trading/Exchange/binance/binance_exchange.py#L61) might help: passing the `recvWindow` param to binance requests. We had to do this on normal binance, there might be the same issue on binanceus.
Are you familiar with python ? If yes then I can explain what to do to fix it yourself. Otherwise you can wait for us to add binanceus to exchanges with specific needs.

**Comment by nathanp83** [comment]
I am familiar with Python, but somebody that is just learning about it. I love a challenge...

**Comment by GuillaumeDSM** [comment]
Ok, then the easiest way should be to replace this line https://github.com/Drakkar-Software/OctoBot-Tentacles/blob/0.4.0/Trading/Exchange/binance/binance_exchange.py#L36 by `return 'binanceus'` in your tentacles/Trading/Exchange/binance/binance_exchange.py
This will transfert the adaptation from regular binance to binanceus. If you don't use regular binance it should be working

<blockquote><img src="https://avatars3.githubusercontent.com/u/38042178?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Drakkar-Software/OctoBot-Tentacles">Drakkar-Software/OctoBot-Tentacles</a></strong></div><div>This repository contains public tentacles (packages) for the OctoBot project - Drakkar-Software/OctoBot-Tentacles</div></blockquote>

**Comment by nathanp83** [comment]
Thank you. That resolved the issue.

**Comment by GuillaumeDSM** [comment]
Thanks to your feedback, BinanceUS exchange now will be available by default starting from the next OctoBot version.
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/312
Thank you @nathanp83 !
